### ISSUE TITLE
Looking for sample project that could be imported as a demo.

### ISSUE THREAD

**Issue by bionictoothpick** [erodozer/tmi.gd#1]
Where do I put my client id and secret?

**Comment by erodozer** [comment]
sorry, I used to have another repo available demonstrating how I use it in my own overlays as reference, but I recently made that private as I began including assets I did not want freely available.

I'll include a new sample project this week as I begin to push up some other updates I have worked on for this lib.

**Comment by erodozer** [comment]
sample project and documentation is now include.  It should be a lot easier to get set up now as well with the most recent changes.
