### ISSUE TITLE
Windows defender detect code as virus

### ISSUE THREAD

**Issue by diecasti** [erodozer/tmi.gd#4]
Just as said, when downloading the code, windows defender analize the package as a virus.

**Comment by erodozer** [comment]
how are you downloading the code?  Windows Defender gives no such report for me, either through git cloning or downloading the zip file directly from github.  There is nothing precompiled or dangerous in this repo that should be triggering any virus detection.

**Comment by diecasti** [comment]
Downloading the zip directly from github.

Im also using Opera GX as my browser.

If I can send you more details I will provide them
